### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Aqshola** [logos-engineer/logos-fest#18]
### Top Bar [ ✔] Solved  -> #1 
- [x] Schedule  
- [x] Speakers
- [x] Registration (Pop Up) #22 
  - [x] Account Log In
  - [x] Make a new Account
 
### Hero Banner [ ✔] Solved -> #1 
- [x] Calendar
- [x] "Logos Fest"
- [x] Register Here
- [x] #26

  
### Event Section [ ✔] Solved -> #1 
- [x] Event Product
  - [x] Justice Bootcamp (Card) and (Page) Issue #21 -> PR #43
  - [x] Justice Talks (Card) and (Page) Issue #14 
- [x] Schedule 

### Output Section  [ ✔] solved -> #10 
- [x] Bunga Rampai
- [x] Buku Braile
    
  
 ### Footer [ ✔] solved -> #4 
- [x] Logo
- [x] Sitemap
- [x] Privacy Policy
- [x] Social Media
- [x] Contact Us
  
### Mobile Responsive
- [x] Top Bar -> Issue #7  PR -> #34 (Dengan footer) 
- [x] Hero Banner -> Issue #7  PR -> #34 (Dengan footer)
- [x] Schedule Section -> #19  PR -> #37 
- [x] Justice Bootcamp -> PR -> #34 (Dengan footer)
- [x] Book Section -> PR -> #37 
- [x] Justice Page -> Issue -> #45 -> PR -> #45
